DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD

Rlog.xcodeproj/project.pbxproj, Rlog/View/Components/CompleteButtonView.swift
|---|---|
|<img src="https://user-images.githubusercontent.com/88080251/196716272-c2a92cc0-6479-4536-a73a-993cfdab8a50.png" width="276" />|<img width="276" alt="image" src="https://user-images.githubusercontent.com/88080251/196716360-9e39a434-723f-4b14-ab68-ada26e2a67c8.png">|
- 근무지 등록 시 사용될 확인 버튼을 구현했습니다.
- 해당 프로세스의 경우 근무지, 시급, 급여일 등 모든 내용이 오류 없이 입력되어야 버튼이 활성화됩니다. 이를 핸들링 할 수 있는 isAvailable 파라미터를 설정했습니다. 
- iOS 15.0 미만 버젼의 경우 overlay를 사용할 수 없어 ZStack을 사용했습니다. [32 : 38]
=> feat : BD-12 확인 버튼을 컴포넌트로 구현했습니다.

Rlog.xcodeproj/project.pbxproj, Rlog/CoreData/CoreDataManager.swift, Rlog/CoreData/DataModel.xcdatamodeld/Rlog.xcdatamodel/contents, Rlog/Model/CoreData/CoreData.swift, Rlog/Model/CoreData/ScheduleEntity+CoreDataClass.swift, Rlog/Model/CoreData/ScheduleEntity+CoreDataProperties.swift, Rlog/Model/CoreData/WorkDayEntity+CoreDataClass.swift, Rlog/Model/CoreData/WorkDayEntity+CoreDataProperties.swift, Rlog/Model/CoreData/WorkspaceEntity+CoreDataClass.swift, Rlog/Model/CoreData/WorkspaceEntity+CoreDataProperties.swift, Rlog/Model/WeekDay.swift, Rlog/Model/WorkspaceColor.swift, Rlog/View/MainTabView.swift
- CoreData Entity 3개 만들었습니다
- CoreData CRUD Logic 작성 하였습니다
- CoreData Test 는 이전 PR 에서 완료 하였기에 생략하였습니다
- 이번 PR 에서 Migration 이 빠졌습니다
- 기존 dev 에서 branch 를 생성하여 다시 coredata 를 implement 하였습니다
=> BD-69-core-data-추가

Rlog/View/Components/StrokeButton.swift
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/9
- 최종 코드 반영 전 머지가 진행되어 새로운 브랜치 생성 후 PR 생성했습니다.
- 제가 놓친 프로세스가 있다면 조언 부탁드립니다.
- N/A
=> BD-16 최종 PR 리뷰 결과에 따라 코드를 리팩토링 합니다.

Rlog.xcodeproj/project.pbxproj, Rlog/Extension/ScheduleListView+.swift, Rlog/View/Schedule/ScheduleListView.swift, Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
|---|---|
|<img src="https://user-images.githubusercontent.com/103025692/196866912-6c42e829-b26a-424a-9660-da962053628c.png" width="276" />|<img width="276" alt="image" src="https://user-images.githubusercontent.com/103025692/196867556-b8a7d5a0-b105-4f17-8d09-aa1a8d76ee56.png"/>|
|<img src="https://user-images.githubusercontent.com/103025692/196866966-9b0c6025-f4fe-4da0-9852-722e0b751a46.png" width="276" />|<img width="276" alt="image" src="https://user-images.githubusercontent.com/103025692/196867750-d4302e2a-7c28-488e-b18d-98a6690135b1.png"/>|
**현재 상단 제목은 수정되었습니다!**
- enum으로 케이스 구현
- LazyVStack으로 리스트 구현
- 하단 그라데이션을 위한 회색 Color Set 추가 필요
- VStack Header 아이콘 수정 필요
- Cell 구현 예정(다른 브랜치에)
=> [FEAT] Schedule 메인 화면 UI 구현

Rlog.xcodeproj/project.pbxproj, Rlog/Rlog.entitlements, Rlog/View/WorkSpace/WorkSpaceCreateView.swift, Rlog/ViewModel/WorkSpace/WorkSpaceCreateViewModel.swift
(수정 및 구현 사항에  대한 간략한 캡쳐)
먼저 피드백 받으면 시간적으로 효율적일것으로 생각되어 올립니다!
|화면1|화면2|
|---|---|
|![Simulator Screen Shot - iPhone 13 - 2022-10-23 at 15 46 41](https://user-images.githubusercontent.com/46256034/197378424-01abe0b5-8714-42bc-b8dd-768bf7d8709f.png)|![Simulator Screen Shot - iPhone 13 - 2022-10-23 at 15 46 14](https://user-images.githubusercontent.com/46256034/197378435-0baf1aec-7634-4eeb-8fcf-3e17e4d8406e.png)|
- 뷰 구현 완료
- 생각했던 작동방식대로 구현됨.
- 간단한 에니메이션 구현
- 다음 뷰로 보내기 위한 모델 구현 완료
- 사용될 컨포넌트를 직접 사용하면서 수정사항이 생길 수 있을것 같습니다.
-
=> BD-25 근무지 등록 UI 구현

Rlog.xcodeproj/project.pbxproj, Rlog/Rlog.entitlements, Rlog/View/WorkSpace/WorkSpaceCreateView.swift, Rlog/ViewModel/WorkSpace/WorkSpaceCreateViewModel.swift
=> Bd 25 근무지 등록 UI 구현

Rlog/CoreData/CoreDataManager.swift, Rlog/CoreData/DataModel.xcdatamodeld/Rlog.xcdatamodel/contents, Rlog/Model/CoreData/ScheduleEntity+CoreDataProperties.swift, Rlog/Model/CoreData/WorkDayEntity+CoreDataProperties.swift
시작 시간, 끝나는 시간은 String 에서 Int16 로 수정
- ScheduleEntity 의 startTime: String, endTime: String -> startHour: Int16, startMinute: Int16, endHour: Int16, endMinute: Int16 으로 변경
- 변경된 attribute 에 맞춰 crud 로직변경
- WorkDayEntity 에 hasDone 추가
- 변경된 attribute 에 맞춰 crud 로직변경
-
-
=> BD-71-core-data-attributes-수정

Rlog/View/Schedule/ScheduleUpdateView.swift, Rlog/ViewModel/Schedule/ScheduleUpdateViewModel.swift
|---|---|
|<img src="https://user-images.githubusercontent.com/103025692/197374345-9c7ed5c1-160b-4420-a37d-dbeda379502e.png" width="276" />|<img width="276" alt="image" src="https://user-images.githubusercontent.com/103025692/197374357-ad06f662-5871-4285-ad85-b6b4e6c31f60.png">|
- UI 구현, 모델 통해 직접 데이터를 넣는 작업을 편하게 하기 위해 body를 각각의 뷰로 나눴습니다.
- viewModel에 4개의 시간 단위를 넣어 TimeEditer로 보내 버튼을 만들었습니다
- Divider, 사유 입력 부분, 삭제 버튼과 시간을 보여주는 부분은 컴포넌트와 Color Asset이 추가로 필요합니다.
- 해야 할 일은 TODO에 주석으로 적었습니다.
=> [FEAT] BD-37 스케줄 수정 UI 구현

Rlog/RlogApp.swift, Rlog/View/Schedule/ScheduleCreateView.swift, Rlog/ViewModel/Schedule/ScheduleCreateViewModel.swift
|---|---|
|<img src="https://user-images.githubusercontent.com/103025692/197575111-e21ca64f-087d-4e16-ba23-21049bcefa27.png" width="276" />|<img width="276" alt="image" src="https://user-images.githubusercontent.com/103025692/197575425-56dc745d-ac55-403c-a0c0-443474987c6a.png"/>|
|<img src="https://user-images.githubusercontent.com/103025692/197575161-86316f93-268e-4ecb-961b-84c482f0582b.png" width="276" />|
- 스케줄 추가 UI만 구현했습니다.
- 근무지 선택 부분은 Custom Toggle로 구현했습니다.
- 나머지 필요한 부분은 TODO로 남겼습니다!
- 네비게이션 바 위치에 한 줄을 어떻게 그을까요...?
- 나머지 컴포넌트가 들어간 다음에 수정하도록 하겠습니다.
- 날짜 변경은 어떻게 할 것인지?
=> Bd 38 스케줄 추가 UI 구현

Rlog.xcodeproj/project.pbxproj, Rlog/View/Components/HDivider.swift
|---|---|
|<img src="https://user-images.githubusercontent.com/88080251/197716413-c4f07080-590e-4c3f-b795-5d587c6afdd2.png" width="276" />|<img width="276" alt="image" src="https://user-images.githubusercontent.com/88080251/197716502-c75a06b1-b3bb-42c7-90d2-974c60d33a54.png">|
- 수평 디바이더 컴포넌트를 구현합니다.
- 세부 컬러 설정이 필요합니다. 가장 마지막 우선순위로 수정할 계획입니다.
- 2022년 10월 25일 오후 5시 기준 dev 브랜치를 클론했습니다.
- 현재 오픈 상태인 BD-17 코드와의 conflict를 고려하여 브랜치를 구성했습니다.
- 오픈되어 있는 BD-17 코드를 병합하다 보니 커밋 수가 많습니다. 효율적으로 관리할 수 있는 방법을 @Junghoon-P 으로 부터 조언 받았습니다.
=> Bd 58 디바이더 만들기

Rlog/Extension/ScheduleListView+.swift, Rlog/View/Schedule/ScheduleListView.swift
|시뮬레이터 화면|피그마 화면|
|---|---|
|<img src="https://user-images.githubusercontent.com/103025692/197726463-47329064-38b4-4ae5-92e4-025179b92f5d.png" width="276" />|<img src="https://user-images.githubusercontent.com/103025692/197723596-5005bd7a-02e3-4520-b7e0-f2aa2db0d53c.png" width="276" />|
|<img src="https://user-images.githubusercontent.com/103025692/197726719-edcb6c12-03c7-4b62-988b-f09a231a7ae4.png" width="276" />|
- ScheduleListView+.swift 내부에 ScheduleCell을 구현했습니다.
- 로직의 경우 view model 정의 후에 구현할 예정입니다.
- isShow 변수는 이후 view model 정의 후에 옮겨질 예정입니다. 지금은 수정 버튼 및 stroke 테스트를 위해 넣었습니다.
- 필요한 todo는 주석으로 넣었습니다.
- isShow의 네이밍, 전체적인 구조?
- 뒷 배경 Rectangle을 어떻게 처리할까요?
=> Bd 36 cell UI 구현

Rlog.xcodeproj/project.pbxproj, Rlog/View/Components/ScheduleContainer.swift
- 근무 일정을 표시하는 컨테이너를 구현했습니다.
- N/A
=> feat : BD-74 ScheduleContainer를 구현합니다.

Rlog/CoreData/CoreDataManager.swift, Rlog/CoreData/DataModel.xcdatamodeld/Rlog.xcdatamodel/contents, Rlog/Extension/DateFormatter+.swift, Rlog/Model/CoreData/ScheduleEntity+CoreDataProperties.swift, Rlog/Model/CreatingScheduleModel.swift, Rlog/Model/CreatingWorkSpaceModel.swift, Rlog/Model/WorkspaceColor.swift, Rlog/View/Components/CustomButtonView.swift, Rlog/View/Components/HDivider.swift, Rlog/View/Components/InputFormElement.swift, Rlog/View/Components/ScheduleContainer.swift, Rlog/View/Components/StrokeButton.swift, Rlog/View/Components/UnderlinedTextField.swift, Rlog/View/WorkSpace/WorkSpaceCreateConfirmationView.swift, Rlog/View/WorkSpace/WorkSpaceCreateCreatingScheduleView.swift, Rlog/View/WorkSpace/WorkSpaceCreateScheduleListView.swift, Rlog/View/WorkSpace/WorkSpaceCreateView.swift, Rlog/View/WorkSpace/WorkSpaceDetailView.swift, Rlog/View/WorkSpace/WorkSpaceListView.swift, Rlog/ViewModel/WorkSpace/WorkSpaceCellViewModel.swift, Rlog/ViewModel/WorkSpace/WorkSpaceCreateConfirmationViewModel.swift, Rlog/ViewModel/WorkSpace/WorkSpaceCreateCreatingScheduleViewModel.swift, Rlog/ViewModel/WorkSpace/WorkSpaceCreateScheduleListViewModel.swift, Rlog/ViewModel/WorkSpace/WorkSpaceCreateViewModel.swift, Rlog/ViewModel/WorkSpace/WorkSpaceDetailViewModel.swift, Rlog/ViewModel/WorkSpace/WorkSpaceListViewModel.swift
- WorkSpaceCreateViewModel 작성 및 구현
- WorkSpaceCreateScheduleListViewModel 작성 및 구현
- WorkSpaceCreateCreatingScheduleViewModel 작성 및 구현
- WorkSpaceCreateConfirmationViewModel 작성 및 구현
-
-
=> BD-79-뷰모델-코어데이터-연동

Rlog/View/Schedule/ScheduleCreateView.swift, Rlog/ViewModel/Schedule/ScheduleCreateViewModel.swift
=> Bd 39 스케줄 추가 로직 구현

Rlog/View/Components/InputFormElement.swift, Rlog/View/Schedule/ScheduleCreateView.swift, Rlog/View/Schedule/ScheduleUpdateView.swift
=> feat : BD-45 컴포턴트 적용

Rlog/View/Schedule/ScheduleCreateView.swift, Rlog/View/Schedule/ScheduleUpdateView.swift, Rlog/View/WorkSpace/WorkSpaceCreateConfirmationView.swift, Rlog/View/WorkSpace/WorkSpaceDetailView.swift, Rlog/View/WorkSpace/WorkSpaceListView.swift, Rlog/ViewModel/WorkSpace/WorkSpaceCreateConfirmationViewModel.swift, Rlog/ViewModel/WorkSpace/WorkSpaceListViewModel.swift
=> BD-91 HotFix

Rlog/View/MainTabView.swift
=> feat : BD-92 UITabBar 컬러 추가

Rlog.xcodeproj/project.pbxproj, Rlog.xcodeproj/xcshareddata/xcschemes/Rlog.xcscheme, Rlog/Rlog.entitlements
=> Bd 90 테스트 플라이트 배포 및 프로비져닝 세팅

Rlog/CoreData/DataModel.xcdatamodeld/Rlog.xcdatamodel/contents, Rlog/Model/CoreData/WorkDayEntity+CoreDataProperties.swift
- WorkEntity의 attributes들의 type 이 변경되었습니다
- startTime: String -> startHour: Int16, startMinute: Int16
- endTime: String -> endHour: Int16, endMinute: Int16
-
-
=> BD-94-workday-entity-시간-형식-수정

Rlog/CoreData/CoreDataManager.swift
- 월에 맞는 workdays 를 모두 return 하는 함수 추가
-
-
-
-
=> BD-93-월별-모든-workday-가져오는-함수-추가

Rlog/CoreData/CoreDataManager.swift
- workspace와 관계없이 모든 schedule 을 가지고오는 함수를 추가했습니다
-
-
-
-
=> BD-101-core-data-manager-get-all-schedules-함수-추가

Rlog.xcodeproj/project.pbxproj, Rlog/Extension/ScheduleListView+.swift, Rlog/Model/WorkDay.swift, Rlog/View/Schedule/ScheduleListView.swift, Rlog/View/Schedule/ScheduleUpdateView.swift, Rlog/ViewModel/Schedule/ScheduleCreateViewModel.swift, Rlog/ViewModel/Schedule/ScheduleListViewModel.swift, Rlog/ViewModel/Schedule/ScheduleUpdateViewModel.swift
- CoreData 사용 안정성을 위해, WorkDay라는 새로운 모델을 만들어 Entity의 값들을 가져와 수정하고 저장하는 방식을 사용하기로 했습니다
- 변수 명도 WorkDayEntity를 사용하는 것은 workDayEntity로, 아닌 것은 workDay로 수정
- WorkDayEntity에 있는 workspace의 경우에는 따로 처리가 불가능합니다...
-
=> Bd 99 custom model 사용 구현

Rlog.xcodeproj/project.pbxproj, Rlog/CoreData/CoreDataManager.swift, Rlog/CoreData/DataModel.xcdatamodeld/Rlog.xcdatamodel/contents, Rlog/Model/CoreData/WorkDayEntity+CoreDataProperties.swift, Rlog/Model/WorkDayType.swift, Rlog/ViewModel/Schedule/ScheduleCreateViewModel.swift, Rlog/ViewModel/Schedule/ScheduleListViewModel.swift, Rlog/ViewModel/Schedule/ScheduleUpdateViewModel.swift
- WorkDatEntity 에 attribute : workDayType 추가
-
-
-
-
=> BD-100-workday-entity-work-type-attributes-추가

Rlog/CoreData/CoreDataManager.swift, Rlog/Extension/ScheduleListView+.swift, Rlog/Model/WorkDay.swift, Rlog/View/Schedule/ScheduleUpdateView.swift, Rlog/ViewModel/Schedule/ScheduleCreateViewModel.swift, Rlog/ViewModel/Schedule/ScheduleListViewModel.swift, Rlog/ViewModel/Schedule/ScheduleUpdateViewModel.swift
- **CoreDataManager 내부 함수 수정이 덜 된 것을 확인해서 이 부분까지 수정했습니다**
- 스케줄 추가, 수정 부분 수정, 리스트뷰에서 시간 보이는 부분 수정
- 빌드, 기능 정상 작동 확인
- WorkDayEntity의 spentTime까지 Double로 바뀌어야 할 것 같습니다, 늦게 파악된 부분에서 죄송합니다...
- 나머지 진행 사항은 이 부분 수정 여부가 결정된 후 반영 및 PR이 올라갈 것 같습니다
=> Bd 102 work day entity 변경에 따른 schedule 관리 부분 수정

Rlog/Model/WorkDay.swift, Rlog/ViewModel/Schedule/ScheduleCreateViewModel.swift, Rlog/ViewModel/Schedule/ScheduleUpdateViewModel.swift
- CoreData의 spentHour의 타입이 Int16에서 Double로 바뀜에 따라 모델과 사용에 대한 변경
- calculateSpentHour 함수 리턴 타입 변경
-
-
=> refactor : BD-102 WorkDay Model 수정

Rlog/View/Schedule/ScheduleCreateView.swift, Rlog/View/Schedule/ScheduleUpdateView.swift
|화면|화면|
|---|---|
|<img src=https://user-images.githubusercontent.com/103025692/199928563-b571059d-1f52-43c1-bd1b-99f44d63ff23.png width=275 />|<img src=https://user-images.githubusercontent.com/103025692/199928576-c6df6c3e-79f5-4bc7-8edf-9e3c06ea10ea.png width=275 />|
- 사유 입력 부분이 키보드로 가리는 문제를 ScrollView를 넣어서 해결
- 이게 맞겠죠?
=> Bd 98 사유 작성 시 화면 가림 수정

Rlog/Extension/ScheduleListView+.swift, Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
- 스케줄 추가, 삭제 시 로직 수정
- 스케줄 확인 시 로직 수정
- `@Published`로 workDay를 바꿔, 확인이 눌러지면 버튼도 사라지도록 구현
- WorkDayEntitiy를 가져오는 함수를 변경
=> Bd 96 스케줄 확인 추가 및 삭제 시 화면 업데이트

Rlog/CoreData/CoreDataManager.swift, Rlog/Extension/Date+.swift, Rlog/View/Schedule/ScheduleListView.swift, Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
|화면|화면|
|---|---|
|<img src=https://user-images.githubusercontent.com/103025692/200243620-06b3f76a-f2fc-48cf-a9c4-829cbd088946.png width=275 />|<img src=https://user-images.githubusercontent.com/103025692/200243626-6cb6ba41-5b25-43bd-b11d-d233dc32bf09.png width=275 />|
- 미래 스케줄에 대해 생성하는 코드 구현
- 처음 앱에 들어올 때 init하도록 설정
- 효율적으로 어떻게 짤까요...?
=> Bd 97 미래 스케줄 더미 구현

Rlog.xcodeproj/project.pbxproj, Rlog/View/Components/FilledButton.swift, Rlog/View/Components/InputFormElement.swift, Rlog/View/Components/UnderlinedTextField.swift, Rlog/View/Schedule/ScheduleListView.swift, Rlog/View/WorkSpace/WorkSpaceListView.swift
하기 사항이 변동 되었습니다.
1. TextField 입력 방식을 generic에서 String으로 변경했습니다.
- CoreData 구조를 준수하기 위해 사용자가 텍스트 필드에 값을 입력할 때, 근무지는 String으로, 시급이나 급여일 같은 숫자 관련 정보는 Int, Int16으로 취급할 필요가 있습니다. 이전의 경우에는 텍스트 필드 입력 타입을 generic으로 설정하여 다양한 타입에 맞게 대응할 수 있도록 했으나, 컴포넌트를 선언한 View와 기대했던 상호작용이 발생하지 않았습니다. (다양한 에러가 발생했습니다. 🥺) 이에 입력 자체는 String으로 관리하되 CRUD를 진행하는 순간에는 Int로 변환하여 로직을 진행하는 것으로 논의했습니다.
현재 확인된 에러 및 에러를 해결하기 위해 시도했던 방안들은 정리하여 공유 드리겠습니다.
2. String 취급 시 예외 상황 관리 
- 시급, 급여일 정보가 String으로 관리됨에 따라 사용자는 숫자 외의 문자열을 입력할 수 있습니다. 화면에 표시되는 키보드를 decimalPad로 하여 우선적으로 예외 상황이 발생하지 않도록 하겠지만, 코드에서도 본 이슈가 발생하지 않도록 처리했습니다.
```swift
// UnderlinedTextField.swift, Line 26 ~
TextField(
textFieldType.placeholder,
text: $text
)
.onChange(of: text) { newValue in
switch textFieldType {
case .workplace:
if text.count == 20 { maximumText = …
```
=> Bd 107 컴포넌트 예외 처리 핸들링

Rlog/CoreData/CoreDataManager.swift
- yearInt, monthInt, dayInt 를 받아서 1달치 workdays 를 돌려주는 함수를 작성하였습니다
예시) getWorkdaysForAMonth(yearInt: 2022, monthInt: 11, dayInt: 5) 
기대되는 리턴 -> 11월5일 부터 12월 5일 미만의 workdays 를 리턴
-
-
=> BD-104-get-work-days-for-a-month-함수-만들기

Rlog/View/WorkSpace/SubViews/WorkSpaceCell.swift, Rlog/View/WorkSpace/WorkSpaceListView.swift
|---|---|
|<img src="https://user-images.githubusercontent.com/77766769/201304375-a87b3806-e509-4372-8e54-db96a08f065e.png" width="276" />|<img width="276" alt="image" src="https://user-images.githubusercontent.com/77766769/201304607-b3873fda-e2fb-410e-96ed-f7aedb7db087.png">|
- 2차 스프린트 디자인 사항 적용
- 디자인 적용 확인을 위해 목데이터 연결
- 근무유형의 경우 데이터 주입후 활용을 위해 로직 주석처리되어 있습니다.
- 해당 부분은 `makeWorkSpaceCardContent` Vstack에 쌓이며, 디자인은 적용이 되어 있습니다.
- 전반적인 assets 이미지 추가는 다른 PR을 통해 진행할 예정입니다.
=> Bd 117 UI 변동사항 간격 컬러 등 반영

Rlog/CoreData/CoreDataManager.swift, Rlog/CoreData/DataModel.xcdatamodeld/DataModel.xcdatamodel/contents, Rlog/CoreData/Model/ScheduleEntity+CoreDataProperties.swift, Rlog/CoreData/Model/WorkdayEntity+CoreDataProperties.swift, Rlog/CoreData/Model/WorkspaceEntity+CoreDataProperties.swift
- WorkdayEntity CRUD 로직 작성
- ScheduleEntity CRUD 로직 작성
- WorkspaceEntity CRUD 로직 작성
-
-
=> Bd 168 CoreData - CoreDataManager CRUD 로직 작성

Rlog/View/MonthlyCalculate/MonthlyCalculateListView.swift, Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateListViewModel.swift
|---|---|
|<img src="https://user-images.githubusercontent.com/103025692/201584958-b8f58d81-71db-4a7f-8a8c-91d9e3f8b3b3.png" width=275 />|<img src="https://user-images.githubusercontent.com/103025692/201584877-c7944097-06b6-466a-a741-b9087caeb46e.png" width=275 />|
- 정산 리스트 뷰의 리스트 셀 UI를 구현했습니다.
- 이후에 데이터 바인딩, 정산 계산 과정 등을 고려했을 때, 하위 Struct와 그냥 변수나 함수 중에 고르기 힘듭니다..
- **이전 PR과 연결되있는 PR(https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/74) 입니다! 전 PR이 머지된 후 수정후 머지가 필요합니다.**
=> Bd 22 각 근무지별 간단 정산 cell UI 구현

Rlog/View/Components/HDivider.swift, Rlog/View/Schedule/ScheduleListView.swift
|---|---|
|<img src="https://user-images.githubusercontent.com/77766769/201605807-627007d2-deb4-481a-a74c-16f0b74a358e.png" width=275 />|<img src="https://user-images.githubusercontent.com/77766769/201602919-c792a6ef-51d2-47c8-8577-d416436a4990.png" width=275 />|
- 디테일 디자인 적용
-
=> BD-172 디자인 디테일 수정

Rlog.xcodeproj/project.pbxproj, Rlog/RlogApp.swift, Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift, Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateDetailViewModel.swift
|---|---|
|<img src="https://user-images.githubusercontent.com/103025692/201595065-444c422e-8235-4d04-9bc4-c381bff1c7ea.png" width=275 />|<img src="https://user-images.githubusercontent.com/103025692/201592878-b2942bd7-b94f-4a33-9fa4-e0a2b7f72a97.png" width=275 />|
- 상단 결산 부분의 UI를 구현했습니다.
- 상단 네비게이션의 경우, 뷰 연결 과정에서 구현할 예정입니다.
- closing 변수 이름 추천 받습니다.
=> Bd 140 정산 결과 UI 구현

Rlog.xcodeproj/project.pbxproj, Rlog/View/Schedule/ScheduleListView.swift, Rlog/View/Schedule/SchedulePendingListView.swift, Rlog/ViewModel/Schedule/SchedulePendingListViewModel.swift
- 해당 월 내 아직 확정되지 않은 근무일정이 있을 경우 SchedulePendingListView에서 모아볼 수 있도록 합니다.
- 이 뷰는 ScheduleListView로 부터 근무일정 데이터를 주입 받습니다.
- SchedulePendingListView가 init 될 때 각 근무일정이 날짜 별로 재배열 되도록 viewModel에서 관리할 예정이나 현재 PR에서는 편의 상 view 자체에서 테스트 로직을 작성했습니다. 아래의 코드를 참고 부탁드립니다.
```swift
// 데이터 선언 시
private let dateArray: [String] = ["11.14", "11.15", "11.20", "11.21"]
private let mockData: [MockModel] = [
MockModel(date: "11.14"),
MockModel(date: "11.15"),
MockModel(date: "11.20"),
MockModel(date: "11.21"),
MockModel(date: "11.51"),
MockModel(date: "12.21"),
MockModel(date: "11.20"),
MockModel(date: "11.21"),
]
private var sortedMockData: [(String, [MockModel])] {
var sortedArray: [(String, [MockModel])] = []
var scheduleArray: [MockModel] = []
for date in dateArray {
for schedule in mockData {
if …
```
=> BD-174 SchedulePendingListView UI

Rlog/View/Schedule/ScheduleCell.swift, Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
|---|---|
|<img src="https://user-images.githubusercontent.com/77766769/201616744-6b512c81-fd90-40db-9782-9ffdc04d90d0.png" width=275 />|<img src="https://user-images.githubusercontent.com/77766769/201616968-d79dda16-0045-4bf9-aba0-316ca8908642.png" width=405 />|
- 근무 카드 디자인 디테일 적용
- 근무카드 패딩 디테일값이 수정되어 디자인 하이파이와 일부 달라 피그마를 캡쳐해서 올렸습니다.
- 카드 이외의 요소는 이전 PR에 적용되어 있습니다.
=> BD-175 근무 카드 디자인 수정

Rlog.xcodeproj/project.pbxproj, Rlog/View/Components/BorderedPicker.swift, Rlog/View/Schedule/ScheduleCreationView.swift, Rlog/View/Schedule/ScheduleListView.swift, Rlog/View/Schedule/SchedulePendingListView.swift, Rlog/ViewModel/Schedule/ScheduleCreationViewModel.swift
N/A
- [PR](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/86) 이전 PR 내용을 반영합니다.
- 부득이한 이슈로 PR이 클로즈 되었습니다. 🥺 왜이럴까요
- 이전 PR 코멘트는 모두 반영되었습니다.
- N/A
-
=> Bd 160 schedule creation view bordered picker pr update

Rlog/View/WorkSpace/WorkSpaceCreateConfirmationView.swift, Rlog/View/WorkSpace/WorkSpaceCreateCreatingScheduleView.swift, Rlog/View/WorkSpace/WorkSpaceCreateScheduleListView.swift, Rlog/View/WorkSpace/WorkSpaceCreateView.swift, Rlog/View/WorkSpace/WorkSpaceListView.swift, Rlog/ViewModel/WorkSpace/WorkSpaceCreateConfirmationViewModel.swift, Rlog/ViewModel/WorkSpace/WorkSpaceCreateCreatingScheduleViewModel.swift, Rlog/ViewModel/WorkSpace/WorkSpaceCreateScheduleListViewModel.swift, Rlog/ViewModel/WorkSpace/WorkSpaceCreateViewModel.swift
https://user-images.githubusercontent.com/46256034/201738746-da97ca55-e672-4b01-b59f-7a6bbf0b2cd8.mp4
|정보를 모두 받은 확인뷰|근무일정이 등록된 뷰|
|---|---|
|![image](https://user-images.githubusercontent.com/46256034/201738366-91c5d5fb-0273-4bda-816f-917cc2c94f30.png)|![image](https://user-images.githubusercontent.com/46256034/201738961-1b5e8d52-e013-4109-a68c-e5b60b8b3895.png)|
- 머지에 따라 컴포넌트 적용이 되었습니다.
- 뷰간연결에 집중해서 진행했습니다.
- 이전 코드를 재활용하여 연결을 복구했기 때문에 diff가 많습니다.
- 예외처리의 경우 다음 PR에서 작업 예정입니다.
-
=> BD-153 근무지 생성 flow 연결했습니다.

Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift, Rlog/View/MonthlyCalculate/MonthlyCalculateListView.swift
- 정산 결과와 근무지 상세 정산 결과를 연결하는 작업했습니다.
- 네비게이션 바를 구현했습니다.
- 빠른 리뷰 부탁드립니다.
=> Bd 182 매월 정산 결과와 근무지 상세 정산 결과 연결

Rlog/View/Schedule/ScheduleCreationView.swift, Rlog/View/Schedule/SchedulePendingListView.swift
|미확인 근무 리스트 캡쳐|근무 추가 캡쳐|
|---|---|
|<img src="https://user-images.githubusercontent.com/77766769/202121084-66c667d0-f47d-45a5-99c6-c36854cc07d7.png" width=275 />|<img src="https://user-images.githubusercontent.com/77766769/202121065-3a55eab7-1e7a-48aa-8f79-f3ec4cb16107.png" width=275 />|
- 근무 미확인뷰 디자인 디테일 수정
- 근무 추가뷰 디자인 디테일 수정
- 미확인뷰의 경우 근무 카드가 컴포넌트로 들어올 예정입니다.
=> Bd 185 schedule pending list view UI 디자인 디테일 추가

Rlog.xcodeproj/project.pbxproj, Rlog/View/MainTabView.swift
- 다크모드 지원 막기 세팅입니다.
- 탭뷰에 불필요한 컬러 하나 추가로 삭제했습니다.
=> Bd 186 다크모드 지원 막기

Rlog/View/Components/InputFormElement.swift, Rlog/View/WorkSpace/SubViews/TitleSubView.swift, Rlog/View/WorkSpace/WorkSpaceCreateConfirmationView.swift, Rlog/View/WorkSpace/WorkSpaceCreateCreatingScheduleView.swift, Rlog/View/WorkSpace/WorkSpaceCreateScheduleListView.swift, Rlog/View/WorkSpace/WorkSpaceCreateView.swift, Rlog/View/WorkSpace/WorkSpaceDetailView.swift, Rlog/View/WorkSpace/WorkSpaceListView.swift, Rlog/ViewModel/WorkSpace/WorkSpaceCreateCreatingScheduleViewModel.swift, Rlog/ViewModel/WorkSpace/WorkSpaceCreateScheduleListViewModel.swift
|근무지등록|근무지등록|근무패턴생성|근무패턴리스트|근무지등록|
|---|---|---|---|---|
|![image](https://user-images.githubusercontent.com/46256034/202163748-c3604062-8734-4797-8d2d-d56bb1f1b19d.png)|![image](https://user-images.githubusercontent.com/46256034/202163997-cfb7a9fe-6b19-4c77-9369-709a638cd07b.png)|![image](https://user-images.githubusercontent.com/46256034/202164075-0e04ad22-fd32-44b5-a434-710248f2f9bf.png)|![image](https://user-images.githubusercontent.com/46256034/202164133-a8084d36-dd09-4e63-8426-81bcc715bed9.png)|![image](https://user-images.githubusercontent.com/46256034/202164179-54e8fa0d-3bcd-4a22-8b7e-f3c608ddfb3b.png)|
|![근무지 등록 화면(정상입력)](https://user-images.githubusercontent.com/46256034/202164764-4702c828-419a-44ef-a01d-4908b53eddd3.png)|![근무지 등록 …
=> BD-131 UI 변동사항 컴포넌트 picker 반영

Rlog/CoreData/CoreDataManager.swift
- CoreDataManager의 createWorkspace 함수가 생성된 WorkspaceEntity를 반환하도록 변경되었습니다
=> BD-188 Workspace - create 완료시 Object 를 반환

Rlog/View/WorkSpace/SubViews/WorkSpaceCell.swift
|시뮬레이터 캡쳐_수정 전|시뮬레이터 캡쳐_수정후|
|---|---|
|<img src="https://user-images.githubusercontent.com/77766769/202366531-2265d14d-e938-4853-b699-d0183ebfc8c7.png" width=275 />|<img src="https://user-images.githubusercontent.com/77766769/202366213-9c696a15-48dd-425a-82b6-0e9fa1315e77.png" width=275 />|
- cornerRadius 적용 (이해를 돕기 위해 수정전 시뮬레이터 배경색을 노랑색으로 처리해놨습니다.)
=> BD-190 근무지셀 코너 스트로크 디테일 수정

Rlog.xcodeproj/project.pbxproj, Rlog/RlogApp.swift, Rlog/View/MainTabView.swift, Rlog/View/MonthlyCalculate/MonthlyCalculateListView.swift, Rlog/ViewModel/ViewRouter.swift
- SwiftUI 기본 탭에서 -> ViewRouter 를 이용한 CustomTab으로 구현
- ViewRouter 파일이 생성되었습니다
- MainTabView 에 @StateObject var viewRouter 이 추가되었습니다
=> BD-191 Custom TabBar 구현

Rlog/View/MainTabView.swift
기본|키보드
:-------------------------:|:-------------------------:
=> BD-192 버튼 겹침 현상 수정

Rlog/View/Components/BorderedPicker.swift, Rlog/View/Components/InputFormElement.swift, Rlog/View/Components/StrokeButton.swift
- @Junghoon-P @song-cool 과 논의 이후 타임 피커의 레이아웃과 디자인을 개선했습니다.
- @Junghoon-P 과 논의 이후 StrokeButton의 destruction 타입 레이아웃을 개선했습니다.
- [Issue](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/issues/101) 이슈를 해결합니다.
- StrokeButton 이름을 ActionButton으로 변경하고자 합니다.
=> BD-193 BorderedPicker 활성화 레이아웃과 애니메이션 / StrokeButton Destruction Type 레이아웃을 개선합니다.

Rlog.xcodeproj/project.pbxproj, Rlog/Assets.xcassets/rlogGreenLogo.imageset/Contents.json, Rlog/Assets.xcassets/rlogGreenLogo.imageset/rlogGreenLogo.svg, Rlog/View/Components/BorderedTextField.swift, Rlog/View/Components/WorkspaceListPicker.swift, Rlog/View/Components/YearMonthStepperCalendar.swift, Rlog/View/Schedule/ScheduleCell.swift, Rlog/View/Schedule/ScheduleCreationView.swift, Rlog/View/Schedule/ScheduleListView.swift, Rlog/View/Schedule/ScheduleUpdateView.swift, Rlog/ViewModel/Schedule/ScheduleCreationViewModel.swift, Rlog/ViewModel/Schedule/ScheduleListViewModel.swift, Rlog/ViewModel/Schedule/ScheduleUpdateViewModel.swift, Rlog/ViewModel/Schedule/TimeManager.swift
https://user-images.githubusercontent.com/88080251/202784843-345cb753-cf1c-4e13-bd70-e9bf43e36d80.mp4
https://user-images.githubusercontent.com/88080251/202784862-0f24df99-8168-4c3d-93cd-b91a1aac6f15.mp4
- 근무지를 생성한 후 일정을 추가 / 수정하는 로직을 개선했습니다.
- 현재 CoreData에 근무 일정을 수정할 수 있는 로직이 없어서, 근무를 삭제하는 영상으로 대체했습니다. @insub4067 과 확인 후 수정 로직 작성 진행하겠습니다.
- [BD-156)(https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/105), [BD-189](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/102) 와 협업을 진행하였습니다. 🔥🔥두 PR을 먼저 진행해주신 후 본 PR을 리뷰 부탁드립니다.🔥🔥
- 코드량이 많은데요..! 아직 오픈되어 있는 PR 작업물들을 연결하다 보니 그런 것 같습니다.. 🥺
- 전체적인 리팩토링이 필요합니다. 우선 로직의 흐름만 보아주시고.. 신속히 코드 정리를 진행할 수 있도록 할게요 🥲
- ScheduleCell의 경우 현재 한 파일 내에 View, ViewModel이 함께 작성되어 있습니다. @jayden000106 과의 협업 중 컨플릭트 방지를 위해 우선적으로 한 파일 내에서 작업을 …
=> Bd 195 근무지 생성 -> 근무 일정 추가 / 수정 로직을 개선합니다.

Rlog/CoreData/CoreDataManager.swift, Rlog/CoreData/DataModel.xcdatamodeld/DataModel.xcdatamodel/contents
- Schedule 삭제시 관계된 workdays 중 hasDone 이 false 은 object 를 삭제하도록 변경 하였습니다
=> BD-200-schedule-삭제시-has-done-이-false-인-workdays-삭제

Rlog/CoreData/CoreDataManager.swift
- WorkdayEntity 를 받아 hasDone 을 toggle 하는 Method 를 추가했습니다
=> BD-202-workday-toggle-has-done-method-추가

Rlog/CoreData/DataModel.xcdatamodeld/DataModel.xcdatamodel/contents, Rlog/ViewModel/ViewRouter.swift
- 미래에 deprecate 에러를 확인하여 수정하였습니다
=> BD-206-repeat-days의-transformer를-ns-secure-unarchive-from-data로-변경

Rlog/CoreData/CoreDataManager.swift
- WorkdayEntity 를 수정할 수 있는 Method 를 추가 했습니다
=> BD-207-workday-entity를-수정할수-있는-method-추가

Rlog/View/Components/YearMonthStepperCalendar.swift, Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift, Rlog/View/MonthlyCalculate/MonthlyCalculateListView.swift, Rlog/View/Schedule/ScheduleCreationView.swift, Rlog/View/Schedule/ScheduleListView.swift, Rlog/View/Schedule/SchedulePendingListView.swift, Rlog/View/WorkSpace/SubViews/WorkSpaceCell.swift, Rlog/View/WorkSpace/WorkSpaceDetailView.swift, Rlog/View/WorkSpace/WorkSpaceListView.swift
- ios15 대응에 따른 네비게이션바 타이틀 무너짐 현상 대응
- 일부뷰 네이게이션바 커스텀
=> Bd 201 qa UI 디테일 검수

Rlog/View/Schedule/ScheduleUpdateView.swift, Rlog/ViewModel/Schedule/ScheduleUpdateViewModel.swift
<div>
</div>
- 근무 수정 뷰 수정(스크롤 뷰로 수정)
- 근무 수정 로직 구현(CoreDataManager와 연결, workday에서 정보 가져와서 보여주기)
- BD-199 PR과 연결되어있습니다
- 시간 선택을 하면 뷰가 깨져서 ScrollView를 추가했습니다.
=> Bd 159 coredata 함수 수정에 따른 호출 함수 수정

Rlog/Extension/Date+.swift, Rlog/Extension/DateFormatter+.swift, Rlog/Model/WorkDayType.swift, Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift, Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateDetailViewModel.swift
| 구현 이미지 | 구현 이미지 | 피그마 이미지 | 
:-------------------------:|:-------------------------:|:-------------------------:
- 정산일 기준 오늘 날짜를 계산하여 기준을 잡아 캘린더의 날짜를 보여줍니다
예시)
경우1 : 정산일 - 20일, 오늘 날짜 - 10월 10일 -> 9월 20일 ~ 10월 19일
경우2 : 정산일 - 20일, 오늘 날자 - 10월 21일 -> 10월 20일 ~ 11월 19일 
- 현재 뷰만 완성 되어 있는 상태입니다.
- 제이든PR (리스트뷰) 가 머지되면 리스트에서 데이터를 바인딩해서 실제 데이터로 로직을 짤 예정입니다.
- 다음 PR에 로직 구현에 따라 일부 뷰가 수정될 수도 있습니다.
=> Bd 209 calendar view 그리기

Rlog/ViewModel/Schedule/ScheduleCreationViewModel.swift
N/A
- 근무지 생성 시 onlyDate가 적용되지 않던 사항을 수정했습니다.
N/A
=> HotFix : BD-219 Update ScheduleCreationViewModel.swift

Rlog/CoreData/CoreDataManager.swift, Rlog/Extension/Date+.swift, Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift, Rlog/View/MonthlyCalculate/MonthlyCalculateListView.swift, Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateListViewModel.swift
<div>
</div>
- 정산에 필요한 정보(상단 이미지 참고)들을 구조체로 따로 만들었습니다.
- ListView에서 월 이동 부분을 컴포넌트로 수정했습니다.
- 주휴수당 계산의 경우에, 따로 브랜치를 파서 진행하겠습니다(내용이 많을 것으로 예상됨)
- Date 관련 내용은 합칠 예정입니다.
=> Bd 10 매월 정산 결과를 확인한다

Rlog/View/Components/WorkspaceListPicker.swift, Rlog/View/Schedule/ScheduleCreationView.swift, Rlog/View/Schedule/ScheduleListView.swift, Rlog/ViewModel/Schedule/ScheduleCreationViewModel.swift
N/A
- 근무 생성 시 자유로운 날짜 변경이 가능하도록 합니다. 
- 근무지가 하나일 시 기본값으로 설정합니다.
- N/A
=> BD-220 근무 일정 생성 프로세스를 개선합니다.

Rlog/View/Schedule/ScheduleCell.swift, Rlog/View/Schedule/ScheduleListView.swift, Rlog/View/Schedule/SchedulePendingListView.swift, Rlog/ViewModel/Schedule/ScheduleCellViewModel.swift
- 확정하기 누르면, 뷰가 업데이트되는 코드 구현
- Schedule Cell이 다른 구조체로 빠져있기 때문에, escaping으로 List View Model에서 업데이트 하도록 구현했습니다.
**- 테오의 #118 PR 중간에서 나온 브랜치입니다. 먼저 머지되고 컨플릭트 해결하고 머지할 예정입니다.**
=> Bd 217 메인화면에서 확인 로직 구현

Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift, Rlog/View/Schedule/ScheduleCreationView.swift, Rlog/View/Schedule/ScheduleListView.swift, Rlog/View/Schedule/ScheduleUpdateView.swift, Rlog/View/WorkSpace/WorkSpaceDetailView.swift
- UX 라이팅 수정
- Hi-Fi 디자인 통일 미흡 부분 보완
=> Bd 212 디자인 검수

Rlog.xcodeproj/project.pbxproj, Rlog/Manager/TimeManager.swift, Rlog/Manager/WorkTypeManager.swift, Rlog/Model/WorkDayType.swift, Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift, Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateCellViewModel.swift, Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateDetailViewModel.swift, Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateListViewModel.swift, Rlog/ViewModel/Schedule/ScheduleCellViewModel.swift, Rlog/ViewModel/Schedule/ScheduleCreationViewModel.swift
=> Bd 227 work type manager 로직 검증 및 수정

Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
- 주간 이동, 월간 이동에 다시 workday를 가져오도록 구현했습니다.
- 이게 맞나?
=> Bd 231 주간 변동 시 날짜에 맞게 자동으로 일정 변경

Rlog/View/Schedule/ScheduleCell.swift, Rlog/View/Schedule/ScheduleListView.swift
|구현| 피그마 |
|---|---|
|<img width="250" alt="image" src="https://user-images.githubusercontent.com/46256034/203926440-994a2e47-de9a-4899-9bc2-23fcbf601cd7.png">|<img width="250" alt="image" src="https://user-images.githubusercontent.com/46256034/203926831-7c7d4688-5c8e-41b3-ad47-d6f9b371197c.png">|
- 확정된 근무셀은 음영처리했습니다.
- 확정된 근무셀의 수정뷰로의 네비게이션을 삭제했습니다.
-
-
-
=> Bd 229 확정된 근무셀 UI구현 선택 비활성화

Rlog/Manager/WorkTypeManager.swift
- 같은 근무지에 같은 요일에 다른 스케쥴 두개가 있을 경우 후에 추가된 스케쥴에 대한 근무일은 추가로 보이는 버그 수정
=> BD-238-define-work-type-로직-수정

Rlog/Manager/WorkTypeManager.swift
- 자동생성으로 만들어진 근무에 대해서만 축소, 연장을 계산하게끔 로직을 개선하였습니다
- 추가로 생성된 근무는 무조건 추가로 들어가게됩니다
=> BD-240-define-work-type-로직-수정

Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift, Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateDetailViewModel.swift
<div>
</div>
<div>
</div>
- 상세 정보를 구현했습니다. 변동이 있는 날짜를 찾아 정보를 보여주도록 수정했습니다.
- 달력의 기준을 Date()에서 CalculateResult 내의 currentMonth로 바꿨습니다. ListView에서 달이 수정되면 수정된 달에 맞는 정보가 보입니다.
- 시급과 주휴수당이 workspace에서 활성화가 되었을 때만 보이도록 설정했습니다.
- 총 급여에 "원"을 붙였습니다.
- 현재 달일 때만 D-Day가 보이도록 수정했습니다.
- MemoCell이 현재는 함수로 구현되어 있는데 생각보다 설정해줘야할게 많아서 다른 View로 빼버려야 할까요?
=> Bd 144 상세 정보 바인딩

Rlog/ViewModel/WorkSpace/WorkspaceCreateScheduleListViewModel.swift
- 근무패턴이 없는경우, 다음버튼을 비활성화 처리했습니다.
- 근무패턴이 모두 삭제되는 경우에도 비활성화 처리를 했습니다.
-
-
-
=> BD-245 근무패턴 없을경우 다음버튼 비활성화 처리

Rlog/View/WorkSpace/WorkspaceCreateScheduleListView.swift
=> BD-246 근무패턴 컴포넌트화

Rlog/ViewModel/WorkSpace/WorkSpaceCreateCreatingScheduleViewModel.swift
- 요일 선택 안된경우, 완료버튼이 눌리지 않도록 처리했습니다.
-
-
-
-
=> BD-247 근무패턴 생성시 예외처리 적용

Rlog/Model/WorkDayType.swift, Rlog/View/MonthlyCalculate/MonthlyCalculateCellView.swift, Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift, Rlog/View/Schedule/ScheduleCell.swift, Rlog/View/Schedule/ScheduleCreationView.swift, Rlog/ViewModel/Schedule/ScheduleCreationViewModel.swift
<div>
</div>
- 근무 겹치는 로직을 만들었습니다.
- startTime, endTime의 날짜가 다르면 적용이 안됩니다.
=> Bd 244 동일 시간 추가 근무 생성 제한

Rlog/View/Components/BorderedPicker.swift, Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift, Rlog/View/Schedule/ScheduleCreationView.swift, Rlog/View/Schedule/ScheduleUpdateView.swift, Rlog/View/WorkSpace/WorkspaceCreateCreatingScheduleView.swift, Rlog/ViewModel/Schedule/ScheduleCreationViewModel.swift, Rlog/ViewModel/Schedule/ScheduleUpdateViewModel.swift
https://user-images.githubusercontent.com/88080251/204212372-0021fdd8-0210-4adf-8ac9-26e332e83b64.mp4
- 하기 파일에 코드 변경이 있습니다.
- ScheduleCreationView, ScheduleUpdateView, WorkspaceCreateCreatingScheduleView
- 상기 뷰의 각 View Model
- willSet을 통해 한 컴포넌트가 active 상태이면 다른 컴포넌트의 바인딩 값은 false 처리되도록 했습니다.
- Bool 의 배열을 선언하여 임의의 인덱스가 true 이면 다른 인덱스는 false 상태로 변하는 것을 처음 시도했는데 순환 참조가 걸리는 것 같더라고요. 이유가 뭘까요?
=> Bd 242 time picker 컴포넌트의 포커스를 핸들링합니다

Rlog.xcodeproj/project.pbxproj, Rlog/Extension/View+.swift, Rlog/View/Components/ShareSheet.swift, Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift, Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateDetailViewModel.swift
🔥 화면 길이를 늘리기 위해 달력을 3개 배치했습니다.
- 정산 상세 화면을 캡쳐하여 공유할 수 있는 기능을 구현했습니다.
- N/A
=> feat : BD-146 화면 캡쳐 및 공유 기능을 구현합니다.

Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift, Rlog/View/WorkSpace/WorkspaceCreateCreatingScheduleView.swift, Rlog/View/WorkSpace/WorkspaceDetailView.swift, Rlog/ViewModel/WorkSpace/WorkSpaceCreateCreatingScheduleViewModel.swift, Rlog/ViewModel/WorkSpace/WorkSpaceDetailViewModel.swift
<div>
</div>
- 요일이 겹치는 스케줄의 생성을 막았습니다.
- 근무지 수정에서는 근무지 수정 화면에서 확인을 눌렀을 때, 근무지 생성에서는 근무패턴 생성 화면에서 Alert를 띄우도록 설정했습니다. 합의된 사항은 아니라서, 추후 수정 가능성이 있습니다.
-
=> Bd 248 겹치는 스케줄이 없는지 확인하기

Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift, Rlog/View/Schedule/ScheduleCreationView.swift, Rlog/View/Schedule/ScheduleListView.swift, Rlog/View/Schedule/ScheduleUpdateView.swift, Rlog/ViewModel/Schedule/ScheduleCreationViewModel.swift, Rlog/ViewModel/Schedule/ScheduleListViewModel.swift, Rlog/ViewModel/Schedule/ScheduleUpdateViewModel.swift
- 근무지가 없을 때, 미확정 근무 확인과 근무 추가 버튼을 비활성화 했습니다.
- 근무 수정에서 기존 근무와 겹치는지 확인하는 로직을 넣었습니다.
- 빌드가 안되는 이슈를 해결했습니다.
-
=> Bd 250 근무지가 없을 때 근무 생성 버튼 비활성화

Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift
- 세금 다른 항목과 다르게 -로 계산됩니다. 이를 명시적으로 표현하여 오해를 막도록 합니다.
- 디자이너와 논의된 내용입니다.
-
-
-
=> feat : BD-253 세금 표현시 -를 표시합니다.

README.md
- 앱스토어 앱 아이콘 규정상 디자인에 그라데이션 백그라운드가 적용되면 안되어 제거한 디자인으로 변경
=> refactor : 리드미 preview 추가

Rlog/Extension/View+.swift
=>  Bd 255 공유 화면을 반복적으로 터치할 시 발생한 앱 크래시를 해결합니다.

README.md, Rlog/Extension/View+.swift
=> BD-255 공유 화면을 반복적으로 터치할 시 발생한 앱 크래시를 해결합니다.
